### PR TITLE
adding in RCM name of MOHC-HadREM3-GA7-05

### PR DESCRIPTION
**Pull request by gredmond-mo**
I have added the above RCM name into the esg.cordex.ini file at the request of Alan Iwi from CEDA in preparation for ingesting Met Office UK CORDEX data. The name is from http://is-enes-data.github.io/CORDEX_RCMs_ToU.txt

### CODE REVIEW

**Comment by alaniwi** [comment]
I don't know if this is enough or whether an addition to `rcm_name_map` further down the file is also needed. I did a successfully test publication using a locally modified `esgf.cordex.ini`, but in this test I had added a line to that table saying `MOHC-HadREM3-GA7-05 | HadREM3`, in addition to the change in https://github.com/ESGF/config/pull/45/commits/8288e9a719fe2239b438b30446247fe4d9ef602a .

Also when I tried publishing, it did not work with the `dataset_id` format on line 23 - I had to change `rcm_name` to `rcm_model`. Any comment on this please @glevava?

**Comment by alaniwi** [comment]
~In particular, it is the `rcm_model` values (rather than the `rcm_name` values) which form part of the dataset ID for existing CORDEX datasets already published.~

**Comment by glevava** [comment]
The dataset ID regex should keep `rcm_name`.
In the `rcm_name_map` you should add `MOHC-HadREM3-GA7-05 | HadREM3-GA7-05`.
Basically, the right column is the same as the left column without the institution name.

**Comment by alaniwi** [comment]
@glevava Thanks. Sorry yes you are right, the existing datasets use `rcm_name`.

(I was confused because I entered an RCM model in CoG e.g. `IPSL-WRF381P` and found some results, but didn't notice that these results did not actually contain that string, only separately `IPSL` and `WRF381P`.)

**Comment by glevava** [comment]
Yes this is a very confusing part of the CORDEX DRS we have to deal with.
Anyway, I merged/updated the esg.cordex.ini file accordingly. ; )

**Comment by alaniwi** [comment]
@glevava Yes I see - thank you also for https://github.com/ESGF/config/commit/a79f2bc788ed799f720b857463a5eb6a6c374279

**Pull request merged**
